
// This file has been generated by the GUI designer. Do not modify.
namespace DriveMirror
{
	public partial class ComboDialog
	{
		private global::Gtk.HBox SelectCombo;

		private global::Gtk.HBox HoriSpliter;

		private global::Gtk.Label lblChoose;

		private global::Gtk.ComboBox ComboList;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DriveMirror.ComboDialog
			this.Name = "DriveMirror.ComboDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child DriveMirror.ComboDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "ComboDlg";
			w1.BorderWidth = ((uint)(2));
			// Container child ComboDlg.Gtk.Box+BoxChild
			this.SelectCombo = new global::Gtk.HBox();
			this.SelectCombo.Name = "SelectCombo";
			this.SelectCombo.Spacing = 6;
			// Container child SelectCombo.Gtk.Box+BoxChild
			this.HoriSpliter = new global::Gtk.HBox();
			this.HoriSpliter.Name = "HoriSpliter";
			this.HoriSpliter.Spacing = 6;
			// Container child HoriSpliter.Gtk.Box+BoxChild
			this.lblChoose = new global::Gtk.Label();
			this.lblChoose.Name = "lblChoose";
			this.lblChoose.LabelProp = global::Mono.Unix.Catalog.GetString("Select One:");
			this.HoriSpliter.Add(this.lblChoose);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.HoriSpliter[this.lblChoose]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child HoriSpliter.Gtk.Box+BoxChild
			this.ComboList = global::Gtk.ComboBox.NewText();
			this.ComboList.WidthRequest = 180;
			this.ComboList.Name = "ComboList";
			this.HoriSpliter.Add(this.ComboList);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.HoriSpliter[this.ComboList]));
			w3.Position = 1;
			this.SelectCombo.Add(this.HoriSpliter);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.SelectCombo[this.HoriSpliter]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w1.Add(this.SelectCombo);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1[this.SelectCombo]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Internal child DriveMirror.ComboDialog.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "MenuArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child MenuArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6[this.buttonCancel]));
			w7.Expand = false;
			w7.Fill = false;
			// Container child MenuArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6[this.buttonOk]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 263;
			this.DefaultHeight = 77;
			this.Show();
			this.ComboList.Changed += new global::System.EventHandler(this.ComboChanged);
		}
	}
}
