
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action DriveMenu;

	private global::Gtk.Action bntConnectLeft;

	private global::Gtk.Action bntDisconnect;

	private global::Gtk.Action bntCreateMirror;

	private global::Gtk.Action bntConnectRigth;

	private global::Gtk.Action bntChangeCredentials;

	private global::Gtk.VBox HorizontalSpliter;

	private global::Gtk.MenuBar MenuBar;

	private global::Gtk.HBox CenterSpliter;

	private global::Gtk.HPaned HoriSplitter;

	private global::Gtk.VBox LeftSpliter;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Entry LeftPathBox;

	private global::Gtk.Button bntLeftOpen;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.NodeView LeftNodeList;

	private global::Gtk.VBox RigthSpliter;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Entry RigthPathBox;

	private global::Gtk.Button bntRigthOpen;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.NodeView RightNodeList;

	private global::Gtk.Statusbar StatusBar;

	private global::Gtk.Label lblStatus;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.DriveMenu = new global::Gtk.Action("DriveMenu", global::Mono.Unix.Catalog.GetString("Drive"), null, "gtk-open");
		this.DriveMenu.ShortLabel = global::Mono.Unix.Catalog.GetString("Drive");
		w1.Add(this.DriveMenu, null);
		this.bntConnectLeft = new global::Gtk.Action("bntConnectLeft", global::Mono.Unix.Catalog.GetString("Connect Left"), null, "gtk-yes");
		this.bntConnectLeft.ShortLabel = global::Mono.Unix.Catalog.GetString("Connect");
		w1.Add(this.bntConnectLeft, null);
		this.bntDisconnect = new global::Gtk.Action("bntDisconnect", global::Mono.Unix.Catalog.GetString("Disconnect"), null, "gtk-no");
		this.bntDisconnect.ShortLabel = global::Mono.Unix.Catalog.GetString("Disconnected");
		w1.Add(this.bntDisconnect, null);
		this.bntCreateMirror = new global::Gtk.Action("bntCreateMirror", global::Mono.Unix.Catalog.GetString("Create Mirror"), null, "gtk-copy");
		this.bntCreateMirror.ShortLabel = global::Mono.Unix.Catalog.GetString("Create Mirror");
		w1.Add(this.bntCreateMirror, null);
		this.bntConnectRigth = new global::Gtk.Action("bntConnectRigth", global::Mono.Unix.Catalog.GetString("Connect Rigth"), null, "gtk-yes");
		this.bntConnectRigth.ShortLabel = global::Mono.Unix.Catalog.GetString("Connect Rigth");
		w1.Add(this.bntConnectRigth, null);
		this.bntChangeCredentials = new global::Gtk.Action("bntChangeCredentials", global::Mono.Unix.Catalog.GetString("Change API Credentials"), null, "gtk-preferences");
		this.bntChangeCredentials.ShortLabel = global::Mono.Unix.Catalog.GetString("Change API Credentials");
		w1.Add(this.bntChangeCredentials, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("DriveMirror");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.HorizontalSpliter = new global::Gtk.VBox();
		this.HorizontalSpliter.Name = "HorizontalSpliter";
		this.HorizontalSpliter.Spacing = 6;
		// Container child HorizontalSpliter.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='MenuBar'><menu name='DriveMenu' action='DriveMenu'><menuitem name='bntConnectLeft' action='bntConnectLeft'/><menuitem name='bntConnectRigth' action='bntConnectRigth'/><menuitem name='bntDisconnect' action='bntDisconnect'/><menuitem name='bntCreateMirror' action='bntCreateMirror'/><menuitem name='bntChangeCredentials' action='bntChangeCredentials'/></menu></menubar></ui>");
		this.MenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/MenuBar")));
		this.MenuBar.Name = "MenuBar";
		this.HorizontalSpliter.Add(this.MenuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.HorizontalSpliter[this.MenuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child HorizontalSpliter.Gtk.Box+BoxChild
		this.CenterSpliter = new global::Gtk.HBox();
		this.CenterSpliter.Name = "CenterSpliter";
		this.CenterSpliter.Spacing = 6;
		// Container child CenterSpliter.Gtk.Box+BoxChild
		this.HoriSplitter = new global::Gtk.HPaned();
		this.HoriSplitter.CanFocus = true;
		this.HoriSplitter.Name = "HoriSplitter";
		this.HoriSplitter.Position = 366;
		// Container child HoriSplitter.Gtk.Paned+PanedChild
		this.LeftSpliter = new global::Gtk.VBox();
		this.LeftSpliter.Sensitive = false;
		this.LeftSpliter.Name = "LeftSpliter";
		this.LeftSpliter.Spacing = 6;
		// Container child LeftSpliter.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.LeftPathBox = new global::Gtk.Entry();
		this.LeftPathBox.CanFocus = true;
		this.LeftPathBox.Name = "LeftPathBox";
		this.LeftPathBox.Text = global::Mono.Unix.Catalog.GetString("/");
		this.LeftPathBox.IsEditable = true;
		this.LeftPathBox.InvisibleChar = '●';
		this.hbox1.Add(this.LeftPathBox);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.LeftPathBox]));
		w3.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.bntLeftOpen = new global::Gtk.Button();
		this.bntLeftOpen.CanFocus = true;
		this.bntLeftOpen.Name = "bntLeftOpen";
		this.bntLeftOpen.UseUnderline = true;
		this.bntLeftOpen.Label = global::Mono.Unix.Catalog.GetString("Open");
		this.hbox1.Add(this.bntLeftOpen);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.bntLeftOpen]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.LeftSpliter.Add(this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.LeftSpliter[this.hbox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child LeftSpliter.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.LeftNodeList = new global::Gtk.NodeView();
		this.LeftNodeList.CanFocus = true;
		this.LeftNodeList.Name = "LeftNodeList";
		this.GtkScrolledWindow1.Add(this.LeftNodeList);
		this.LeftSpliter.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.LeftSpliter[this.GtkScrolledWindow1]));
		w7.Position = 1;
		this.HoriSplitter.Add(this.LeftSpliter);
		global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.HoriSplitter[this.LeftSpliter]));
		w8.Resize = false;
		// Container child HoriSplitter.Gtk.Paned+PanedChild
		this.RigthSpliter = new global::Gtk.VBox();
		this.RigthSpliter.Sensitive = false;
		this.RigthSpliter.Name = "RigthSpliter";
		this.RigthSpliter.Spacing = 6;
		// Container child RigthSpliter.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.RigthPathBox = new global::Gtk.Entry();
		this.RigthPathBox.CanFocus = true;
		this.RigthPathBox.Name = "RigthPathBox";
		this.RigthPathBox.Text = global::Mono.Unix.Catalog.GetString("/");
		this.RigthPathBox.IsEditable = true;
		this.RigthPathBox.InvisibleChar = '●';
		this.hbox2.Add(this.RigthPathBox);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.RigthPathBox]));
		w9.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.bntRigthOpen = new global::Gtk.Button();
		this.bntRigthOpen.CanFocus = true;
		this.bntRigthOpen.Name = "bntRigthOpen";
		this.bntRigthOpen.UseUnderline = true;
		this.bntRigthOpen.Label = global::Mono.Unix.Catalog.GetString("Open");
		this.hbox2.Add(this.bntRigthOpen);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.bntRigthOpen]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.RigthSpliter.Add(this.hbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.RigthSpliter[this.hbox2]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child RigthSpliter.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.RightNodeList = new global::Gtk.NodeView();
		this.RightNodeList.CanFocus = true;
		this.RightNodeList.Name = "RightNodeList";
		this.GtkScrolledWindow2.Add(this.RightNodeList);
		this.RigthSpliter.Add(this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.RigthSpliter[this.GtkScrolledWindow2]));
		w13.Position = 1;
		this.HoriSplitter.Add(this.RigthSpliter);
		this.CenterSpliter.Add(this.HoriSplitter);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.CenterSpliter[this.HoriSplitter]));
		w15.Position = 0;
		this.HorizontalSpliter.Add(this.CenterSpliter);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.HorizontalSpliter[this.CenterSpliter]));
		w16.Position = 1;
		// Container child HorizontalSpliter.Gtk.Box+BoxChild
		this.StatusBar = new global::Gtk.Statusbar();
		this.StatusBar.Name = "StatusBar";
		this.StatusBar.Spacing = 6;
		// Container child StatusBar.Gtk.Box+BoxChild
		this.lblStatus = new global::Gtk.Label();
		this.lblStatus.Name = "lblStatus";
		this.lblStatus.LabelProp = global::Mono.Unix.Catalog.GetString("<span foreground=\"#FF0000\">Not Connected</span>");
		this.lblStatus.UseMarkup = true;
		this.StatusBar.Add(this.lblStatus);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.StatusBar[this.lblStatus]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		this.HorizontalSpliter.Add(this.StatusBar);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.HorizontalSpliter[this.StatusBar]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		this.Add(this.HorizontalSpliter);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 741;
		this.DefaultHeight = 512;
		this.Show();
		this.bntConnectLeft.Activated += new global::System.EventHandler(this.OnConnectLeftClicked);
		this.bntDisconnect.Activated += new global::System.EventHandler(this.OnDisconnectClicked);
		this.bntCreateMirror.Activated += new global::System.EventHandler(this.OnCreateMirrorClicked);
		this.bntConnectRigth.Activated += new global::System.EventHandler(this.OnConnectRigthClicked);
		this.bntChangeCredentials.Activated += new global::System.EventHandler(this.ChangeCredentialsClicked);
		this.bntLeftOpen.Clicked += new global::System.EventHandler(this.OnLeftOpenClicked);
		this.LeftNodeList.RowActivated += new global::Gtk.RowActivatedHandler(this.OnLeftRowActivated);
		this.LeftNodeList.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler(this.OnLeftClickRelease);
		this.bntRigthOpen.Clicked += new global::System.EventHandler(this.OnRigthOpenClicked);
		this.RightNodeList.RowActivated += new global::Gtk.RowActivatedHandler(this.OnRigthRowActivated);
		this.RightNodeList.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler(this.OnRigthClickRelease);
	}
}
